export enum ExpensesActionTypes {
  GET_EXPENSES = 'GET_EXPENSES',
  SET_EXPENSES_FROM_TIME_PERIOD = 'SET_EXPENSES_FROM_TIME_PERIOD',
  SET_EXPENSES_FROM_GIVEN_DAY = 'SET_EXPENSES_FROM_GIVEN_DAY',
  SET_EXPENSES_FROM_CHOSEN_MONTH = 'SET_EXPENSES_FROM_CHOSEN_MONTH',
}
