export enum ActionTypes {
  GET_EXPENSES = 'GET_EXPENSES',
  SET_EXPENSES_FROM_X_DAYS_AGO = 'SET_EXPENSES_FROM_X_DAYS_AGO',
  GET_REVENUES = 'GET_REVENUES',
  SET_REVENUES_FROM_X_DAYS_AGO = 'SET_REVENUES_FROM_X_DAYS_AGO',
  GET_DATA_START = 'GET_DATA_START',
  GET_DATA_ERROR = 'GET_DATA_ERROR',
  UPDATE_DATA_START = 'UPDATE_DATA_START',
  UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL',
}
