export enum ActionTypes {
  GET_EXPENSES = 'GET_EXPENSES',
  SET_EXPENSES_FROM_X_DAYS_AGO = 'SET_EXPENSES_FROM_X_DAYS_AGO',
  GET_INCOMES = 'GET_INCOMES',
  SET_INCOMES_FROM_X_DAYS_AGO = 'SET_INCOMES_FROM_X_DAYS_AGO',
  GET_DATA_START = 'GET_DATA_START',
  GET_DATA_ERROR = 'GET_DATA_ERROR',
  UPDATE_DATA_START = 'UPDATE_DATA_START',
  UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL',
  SET_EXPENSES_FROM_GIVEN_DAY = 'SET_EXPENSES_FROM_GIVEN_DAY',
  SET_EXPENSES_FOR_CHOSEN_MONTH = 'SET_EXPENSES_FOR_CHOSEN_MONTH',
  SET_INCOMES_FOR_CHOSEN_MONTH = 'SET_INCOMES_FOR_CHOSEN_MONTH',
}
