export enum ActionTypes {
  GET_EXPENSES = 'GET_EXPENSES',
  GET_REVENUES = 'GET_REVENUES',
  UPDATE_DATA_START = 'UPDATE_DATA_START',
  UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL',
}
