export enum SharedActionTypes {
  GET_DATA_START = 'GET_DATA_START',
  GET_DATA_ERROR = 'GET_DATA_ERROR',
  UPDATE_DATA_START = 'UPDATE_DATA_START',
  UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL',
  SET_CHOSEN_MONTH = 'SET_CHOSEN_MONTH',
}
